export const todaysProduct = [
  {
    id: 51,
    name: "HAVIT HV-G92 Gamepad",
    price: 100,
    discount: 50,
    image: "/img/today_1.png",
  },
  {
    id: 52,
    name: "AK-900 Wired Keyboard",
    price: 200,
    discount: 25,
    image: "/img/today_2.png",
  },
  {
    id: 53,
    name: "IPS LCD Gaming Monitor",
    price: 300,
    discount: 90,
    image: "/img/today_3.png",
  },
  {
    id: 54,
    name: "S-Series Comfort Chair",
    price: 400,
    discount: 15,
    image: "/img/today_4.png",
  },
  {
    id: 55,
    name: "AK-900 Wired Keyboard",
    price: 500,
    discount: 80,
    image: "/img/today_2.png",
  },
  {
    id: 56,
    name: "IPS LCD Gaming Monitor",
    price: 600,
    discount: 35,
    image: "/img/today_3.png",
  },
  {
    id: 57,
    name: "HAVIT HV-G92 Gamepad",
    price: 700,
    discount: 40,
    image: "/img/today_1.png",
  },
  {
    id: 58,
    name: "AK-900 Wired Keyboard",
    price: 800,
    discount: 45,
    image: "/img/today_2.png",
  },
  {
    id: 59,
    name: "S-Series Comfort Chair",
    price: 900,
    discount: 50,
    image: "/img/today_4.png",
  },
  {
    id: 60,
    name: "HAVIT HV-G92 Gamepad",
    price: 1100,
    discount: 60,
    image: "/img/today_1.png",
  },
  {
    id: 61,
    name: "IPS LCD Gaming Monitor",
    price: 1200,
    discount: 65,
    image: "/img/today_3.png",
  },
  {
    id: 61,
    name: "AK-900 Wired Keyboard",
    price: 300,
    discount: 70,
    image: "/img/today_2.png",
  },
  {
    id: 63,
    name: "  HAVIT HV-G92 Gamepad",
    price: 400,
    discount: 75,
    image: "/img/today_1.png",
  },
  {
    id: 64,
    name: "IPS LCD Gaming Monitor",
    price: 500,
    discount: 80,
    image: "/img/today_2.png",
  },
  {
    id: 65,
    name: "    AK-900 Wired Keyboard",
    price: 600,
    discount: 85,
    image: "/img/today_3.png",
  },
  {
    id: 66,
    name: "AK-900 Wired Keyboard",
    price: 900,
    discount: 90,
    image: "/img/today_1.png",
  },
  {
    id: 67,
    name: "IPS LCD Gaming Monitor",
    price: 800,
    discount: 95,
    image: "/img/today_3.png",
  },
  {
    id: 68,
    name: "S-Series Comfort Chair",
    price: 800,
    discount: 100,
    image: "/img/today_4.png",
  },
  {
    id: 69,
    name: "IPS LCD Gaming Monitor",
    price: 1000,
    discount: 105,
    image: "/img/today_2",
  },
];
