const products = [
  // {
  //   name: "Gucci duffle bag",
  //   image: "img/bag.png",
  //   discountedPrice: 960,
  //   originalPrice: 1160,
  //   discount: "-35%",
  // },
  {
    id: 1,
    name: "AK-900 Wired Keyboard",
    image: "img/keyboard.png",
    discountedPrice: 200,
    price: 200,
    rating: 65,
  },
  {
    id: 2,
    name: "RGB liquid CPU Cooler",
    image: "img/speaker.png",
    discountedPrice: 1960,
    price: 1960,
    discount: "-35%",
  },
  {
    id: 3,
    name: "GP11 Shooter USB Gamepad",
    image: "img/game.png",
    discountedPrice: 550,
    price: 550,
    discount: "-35%",
  },
  {
    id: 4,
    name: "Quilted Satin Jacket",
    image: "img/jacket.png",
    discountedPrice: 750,
    price: 750,
    discount: "-35%",
  },
  {
    id: 5,
    name: "IPS LCD Gaming Monitor",
    image: "img/screen.png",
    discountedPrice: 1960,
    price: 1160,
    discount: "-35%",
    rating: 65,
  },
  // {
  //   name: "ASUS FHD Gaming Laptop",
  //   image: "img/pc.png",
  //   discountedPrice: 960,
  //   originalPrice: null,
  //   rating: 65,
  // },
  {
    id: 6,
    name: "Quilted Satin Jacket",
    image: "img/jacket.png",
    discountedPrice: 750,
    price: 750,
    discount: "-35%",
  },
  // {
  //   name: "HAVIT HV-G92 Gamepad",
  //   image: "/img/today_2.png",
  //   discountedPrice: 960,
  //   originalPrice: null,
  //   isNew: true,
  //   rating: 65,
  // },
  {
    id: 7,
    name: "RGB liquid CPU Cooler",
    image: "img/speaker.png",
    discountedPrice: 1960,
    price: 1960,
    discount: "-35%",
  },
  {
    id: 8,
    name: "AK-900 Wired Keyboard",
    image: "img/keyboard.png",
    discountedPrice: 200,
    price: 200,
    rating: 65,
  },
];

export default products;
